### ISSUE TITLE
Using System Env variables when running

### ISSUE THREAD

**Issue by pkordes** [karatelabs/vscode-extension#12]
I am highly dependent on system environment variables within the tests and cannot seem to add them to the vscode extension runs.  env is not supported in the launch.json.  Note that they are values I am getting using java.lang.system.getEnv() from within the features.  I am calling everything standalone.  Is there a way to do this that I just can't find?

**Comment by ptrthomas** [comment]
@pkordes thanks for reporting this, I think we will have to add this to the `Run Options` as documented here: https://github.com/karatelabs/karate-vscode-extension#run-options - and a heads up, as of now this easy-access run-options is a premium feature

this is indeed missing currently.

as a workaround, I think the only option is to use a shell script and the stand-alone JAR. something like this: https://github.com/karatelabs/karate/blob/v1.3.0/examples/zip-release/karate

I modified the script to be this, but you can surely find a way of passing arguments:

```bash
#!/bin/bash
export MY_ENV=foo
java -cp "$(dirname "$0")/karate.jar":. com.intuit.karate.Main "$@"
```

then you can do this in the terminal:
```sh
./karate.sh some/dir/some.feature
```

given this feature file:
```cucumber
Feature:

Scenario:
* print 'my env is:', java.lang.System.getenv('MY_ENV')
```

it works

this is surprisingly a hard problem to solve in an elegant way in the plugin. for context, see these ideas including inventing an IDE-neutral equivalent of a "launch profile" that is baked into the karate runtime:

https://github.com/karatelabs/karate/issues/2208

happy to get your thoughts and suggestions

**Comment by pkordes** [comment]
I took a look at everything around karatelabs/karate#2208, however, this seems a little tangential. I guess I could get behind the .karate folder if it indeed supported an "env" section for run configurations.  The main issue I have right now would be solved by including support for .env in the launch configuration in vscode.  There is indeed the idea of a launch configuration specific to karate from what I could see.  It even uses intellisense to provide some of the options that you can add.  I couldn't find any documentation on what any of those options do.

My use case is such that we are looking to use Karate as a "validation" engine that can pull security scans and run automated validation on the results.  Running in CI will always give the ability to inject sensitive tokens via envvar but I simply can't test these in VSCode at all via the "Run".  I have no trouble adding exports to the terminal and invoking the jar.  I just wish there was a simpler way to click "Run" and have it pickup a launch config.  I am not too familiar with writing a vscode plugin but happy to give it a go!

**Comment by ptrthomas** [comment]
@pkordes this helps. you are right, we should support this at least in the launch config and we will prioritize that for the next release. I will also explore how to quick-access this next to the `Run` codelens

**Comment by ptrthomas** [comment]
version 1.0 has been released and this includes native support for VS Code Launch configurations as a paid feature

you can read about how it works here: https://github.com/karatelabs/karate-vscode-extension#launch-configurations
