### ISSUE TITLE
Scenario outline example variable in configure header break syntax coloring

### ISSUE THREAD

**Issue by rc2201** [karatelabs/vscode-extension#13]
To replicate-

``
Feature: karate answers 2

Background:
  * url 'http://localhost:8080'

Scenario Outline: given circuit name, validate country
  Given path 'api/f1/circuits/<name>.json'
  When method get
  Then match $.MRData.CircuitTable.Circuits[0].Location.country == '<country>'

  Examples:
    | name   | country  |
    | monza  | Italy    |
    | spa    | Belgium  |
    | sepang | Malaysia |
``
![Screen Shot 2023-04-20 at 1 46 51 PM](https://user-images.githubusercontent.com/63313757/233550906-0e9a1ee2-dc81-4489-8fd1-c43147fafe64.png)

**Comment by ptrthomas** [comment]
@varunc04 as far as I can tell this works fine in the v0.8.0 version of the plugin, can you make sure you have the latest version from the marketplace ?

**Comment by rc2201** [comment]
Hi @ptrthomas I am using the latest version i.e. 0.8.0.

**Comment by ptrthomas** [comment]
ok I looked more closer at the image. `* configure headers = <name>` is no longer recommended use, you can do this instead: `* configure headers = name` - because `name` will be a valid variable: https://github.com/karatelabs/karate#scenario-outline-enhancements

**Comment by rc2201** [comment]
Thanks, @ptrthomas. That worked.
