### ISSUE TITLE
How do we run tests via the extension and also use karate-config.js?

### ISSUE THREAD

**Issue by ammar01** [karatelabs/vscode-extension#14]
Hi, 

I downloaded a copy of the files from https://github.com/karatelabs/karate-npm and after expanding it, I opened it in VSCode. 
I was able to get the httpbin.feature test to run and pass via the extension by adding `* configure ssl = true` to it. 
I wanted to set this globally so I added `karate.configure('ssl', true);` to karate-config.js. 
After removing the configuration line from the test, and clicking the extension's Run button, the test failed, indicating it had not processed the karate-config.js file. 
How do we set the extension execution to use the karate-config.js file?

Thanks,
Ammar.

**Comment by ptrthomas** [comment]
by default, the `karate-config.js` is looked for in the project folder. for example see screenshot below, just 2 files and it works as expected:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/915480/234751192-6df311db-1dc1-4760-8cc4-75d7ec5a130a.png">

you can also try changing this setting:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/915480/234751440-b7e67a4a-2f9a-4728-92be-4e570a96e646.png">

**Comment by ammar01** [comment]
Thank you Peter, adding the config file path into the Extension's "Classpath Prefix" field did the trick!

**Comment by ptrthomas** [comment]
@ammar01 great !

**Comment by ptrthomas** [comment]
for those looking for how to switch the run-mode to `maven` navigate via the `Extensions` icon in the main toolbar (typically on the left), click on the "gear" icon, select `Extension Settings` and you will see options to change them, including the drop-down for `Run: Mode`, see screenshot below:

![image](https://github.com/karatelabs/karate-vscode-extension/assets/915480/3a463b06-ba90-4120-906e-ccc99a704308)

**Comment by AgileScrum** [comment]
Thank you so much Peter 👍
