### ISSUE TITLE
karate-config.js is not recognized in a VS Code workspace

### ISSUE THREAD

**Issue by logicinplay** [karatelabs/vscode-extension#16]
Re-posting [SO question](https://stackoverflow.com/questions/77006623/how-to-change-specify-vs-code-karate-runner-extension-project-directory) here.

> I have a workspace in VS Code with the following folders:
> [VS Code Workspace](https://i.stack.imgur.com/EBLID.png)
> When running the feature file, it was not able to detect my karate/karate-config.js file. On the karate tab, it is showing the "project" folder (see image below). And, all test reports are saved in "project" folder.
> [Karate Runner Tab](https://i.stack.imgur.com/zCU9F.png)
> I tried to re-arrange the folders in my workspace, moving the "karate" folder to the top, and everything works fine.

It seems that the karate runner only looks for the `karate-config.js` in the first folder in VS Code workspace. Hence, it is failing to read karate config file when it is in another folder other than the first.

Sample workspace: [karate-replicate.zip](https://github.com/karatelabs/karate-vscode-extension/files/12492031/karate-replicate.zip)

The zip file contains the following:
- `karate-config.js` - returns json object: `{ myVariable: "Hello World!" }`
- `hellp-world.feature` - prints the value of `myVariable` configured in `karate-config.js`
- `working-workspace.code-workspace` - VS Code workspace where `karate` folder is at the top/first. This workspace runs karate test without any issue.
- `error-workspace.code-workspace` - VS Code workspace where `karate` folder is at the botoom/last. This workspace runs karate and will throw not defined error

_Using working-workspace.code-workspace:_
![image](https://github.com/karatelabs/karate-vscode-extension/assets/143767378/1e6bd901-d34b-4853-b888-8fd95bf72184)

_Using error-workspace.code-workspace:_
![image](https://github.com/karatelabs/karate-vscode-extension/assets/143767378/b987f333-7b89-4cec-b1ef-6ea5f8eeff90)

I tried changing [classprefix](https://github.com/karatelabs/karate-vscode-extension/issues/14#issuecomment-1524593692) but to no avail.

My work around is creating another workspace just for karate and everything works fine but, if this can be fixed, that would really be appreciated. Thank you!

**Comment by ptrthomas** [comment]
latest version natively supports java projects (maven, gradle) so should be fixed
