### ISSUE TITLE
Why was PLUS/PRO feature added?

### ISSUE THREAD

**Issue by morbror** [karatelabs/vscode-extension#18]
Why was PLUS/PRO feature added? Really sad to see this kind of bait and switch...

**Comment by ptrthomas** [comment]
This is not a bait and switch. Karate open-source remains free and under the MIT license. Users/teams/Enterprise can continue to download and use Karate open-source using [Maven](https://github.com/karatelabs/karate/wiki/Get-Started:-Maven-and-Gradle#maven), [Gradle](https://github.com/karatelabs/karate/wiki/Get-Started:-Maven-and-Gradle#gradle), [Standalone Jar](https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options#standalone-jar), [Docker](https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options#docker), [NPM](https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options#npm) and [JBang](https://github.com/karatelabs/karate/wiki/Get-Started:-Other-Runtime-Options#jbang).
 
For the in-IDE experience there are two pricing tiers PLUS and PRO.
 
We need our users to appreciate Karate Labs is not in the game of market valuation and wants to scale a company on strong values and principles.
