### ISSUE TITLE
Error "org.graalvm.polyglot.PolyglotException: ReferenceError: "baseUrl" is not defined" thrown when trying to run

### ISSUE THREAD

**Issue by w5lurz** [karatelabs/vscode-extension#2]
I am having a simple karate-config.js file where i have a baseUrl inside config object.
baseUrl is surely defined, yet it throws this error.

Trying to run on system:
- Windows 10
- VSCode 1.71.2
- Karate extension v0.2.0

**Comment by ptrthomas** [comment]
@w5lurz would you be able to provide a simple sample project ? is the `karate-config.js` in the root of the project ?

**Comment by ptrthomas** [comment]
0.4.0 was just published that fixes this, should be on the marketplace shortly

we now add the workplace root to the classpath, and this can be customized via the vscode extension settings
