### ISSUE TITLE
JsonPath filter syntax causes colouring to break for remainder of the open file

### ISSUE THREAD

**Issue by leonluc-dev** [karatelabs/vscode-extension#3]
There seems to be an issue with syntax colouring whenever using the JsonPath filter syntax.
As can be seen here:
![afbeelding](https://user-images.githubusercontent.com/5390147/197798055-3c2d7a65-b8a3-4ca6-aba8-71c7a309c87c.png)
as compared to the colouring when not using JsonPath syntax:
![afbeelding](https://user-images.githubusercontent.com/5390147/197797853-ca3864fb-6652-49f0-9824-899d37e0bab3.png)

More specifically it's the `?` symbol in the syntax that seems to be causing it.

**Comment by ptrthomas** [comment]
@leonluc-dev thanks for reporting this ! will look into it

**Comment by ptrthomas** [comment]
0.4.0 was just published that fixes this, should be on the marketplace shortly
