### ISSUE TITLE
Support for Linux ARM 64

### ISSUE THREAD

**Issue by cheanwei** [karatelabs/vscode-extension#5]
I am trying to install the extension on the dev container which is Linux arm64 architecture. I got following error message:
`The 'karatelabs.karate' extension is not available in Visual Studio Code for Linux ARM 64.`

**Comment by ptrthomas** [comment]
@cheanwei yes, we can consider this. can you explain your environment so that I can understand better ?

**Comment by ptrthomas** [comment]
@cheanwei we have created an interim release, can you try manually installing from here: https://github.com/karatelabs/karate-vscode-extension/releases/tag/v0.7.0

if you can confirm it works, we will start releasing this to the marketplace from the next version onwards

**Comment by cheanwei** [comment]
Following is the information I copy from my local Visual Studio Code "About" dialog box.

Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

I am using the VSCode devcontainer remote development feature. The dev container image I connected to is `mcr.microsoft.com/devcontainers/base:bullseye`. The image is also arm64 architecture.

I downloaded the interim release karate-linux-arm64-0.7.0.vsix and install it into the remote container from VSCode option menu. Then, I reload the VSCode window and try to run a Karate Scenario. I get this error message "qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory".

**Comment by ptrthomas** [comment]
@cheanwei that sounds to me that maybe you have a mismatch somewhere. I'm sorry that I don't have enough info to help. I suggest you try using a different image or work normally. We will anyway release an arm version in the next release for wider feedback

**Comment by ptrthomas** [comment]
@cheanwei as per the info you provided maybe you should be using Darwin ARM ?

**Comment by ptrthomas** [comment]
@cheanwei please ignore my 2 comments above, and thank you for reporting this, I found an issue with our build process. I fixed it and was able to test this working on my local mac m1 - which I think is the exact same config as yours. please redownload the `karate-linux-arm64-0.7.0.vsix` from the releases again and try, it should work: https://github.com/karatelabs/karate-vscode-extension/releases/tag/v0.7.0

please let me know so I can confirm it works ! thanks again

**Comment by cheanwei** [comment]
Yes. It works now.

**Comment by ptrthomas** [comment]
@cheanwei thanks for confirming ! I will close this now. from the next version 0.8.0 onwards will be releasing `linux-arm64` also to the marketplace
