### ISSUE TITLE
Report link can not be clicked in VSCode Remote Development Environment

### ISSUE THREAD

**Issue by cheanwei** [karatelabs/vscode-extension#6]
I am trying to run the Karate test in VSCode Dev Container. The Karate plugin show a report link after the test finished. However it cannot be clicked. Neither the "Open in Browser" link nor the link that show the actual path below works.

![image](https://user-images.githubusercontent.com/5423496/219381776-095547e2-0727-400c-8626-8caac84dca66.png)

**Comment by ptrthomas** [comment]
@cheanwei that's right - if you upgrade to the paid plugin you will be able to open the report in a separate tab. you can see a demo here: https://youtu.be/aJ7WdHM1t94

the`Open In Browser` link should probably be hidden if we are in a remote container, so I will leave this ticket open to track that

**Comment by ptrthomas** [comment]
fixed in 0.8.0 just released
