### ISSUE TITLE
Question/Suggestion: Does vscode free or paid plugin support autoformat?

### ISSUE THREAD

**Issue by carlos-vargas-pplus** [karatelabs/vscode-extension#8]
Hi, im using both intellij free plugin and vscode free extension

Seems intellij free plugin can format the `.feature` file but the vscode does not support that (or do not know how to trigger it)

Does the format code (feature file) (not json one) for vscode extension comes on paid plugin?

**Comment by ptrthomas** [comment]
@carlos-vargas-pplus we need to add this support for the free plugin. if you can provide a comparison point as to how other plugins support it, we will be happy to use that as a reference. we will use this ticket to track this improvement. thanks for the feedback and please keep it coming

**Comment by carlos-vargas-pplus** [comment]
hi mr thomas,
Since is for the vscode free tier extension I think will be ok as long as it formats like free tier karate plugin from IntelliJ

**Comment by ptrthomas** [comment]
0.8.0 just released supports code formatting in the free version itself

**Comment by carlos-vargas-pplus** [comment]
thanks!
